[package]
name = "cava-raw-reader"
version = "0.2.2"
edition = "2024"
description = "Read cava output in raw mode"
repository = "https://github.com/REVO9/cava-raw-reader.git"
license = "MIT"

[dependencies]
async-stream = "0.3.6"
futures = "0.3.34"
rust-ini = "0.21.3"
tempfile = "3.27.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["io-util", "process", "sync"] }

[dev-dependencies]
cava-raw-reader = { path = ".", features = ["full"] }
crossterm = "0.29.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }

[features]
full = ["watcher"]
watcher = []
